    
name: Prod | Detect and Publish Module Changes

on:
  push:
    branches:
      - master
    paths:
      - 'modules/**'
      - '!modules/**/example**'
      - '!modules/**/README.md'

  pull_request:
    branches:
      - master
    paths:
      - 'modules/**'
      - '!modules/**/example**'
      - '!modules/**/README.md'

          
env:
  FOLDER_PREFIX: "modules/"

jobs:
  detect_changes:
    name: Detect changes
    runs-on: 'ubuntu-latest'
    outputs:
      module_changes: ${{ steps.get_diff.outputs.module_changes }}
      module_folder: ${{ steps.get_diff.outputs.module_folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Diff
        id: get_diff
        shell: pwsh
        run: |
          . ./.scripts/Get-ChangedVersions.ps1

          $outputs = Get-ChangedVersions -EventName "${{ github.event_name }}" -FolderPrefix $env:FOLDER_PREFIX

          # Set outputs
          "module_changes=$($outputs.ModuleChanges)" >> $env:GITHUB_OUTPUT
          "module_folder=$($outputs.FolderPrefix)" >> $env:GITHUB_OUTPUT

  verify_solution:
    needs: 
    - detect_changes
    if: github.event_name == 'pull_request' && fromJson(needs.detect_changes.outputs.module_changes) != ''
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect_changes.outputs.module_changes) }}
    
    uses: ./.github/workflows/tmpl.bicep.module.verify.pwsh.yaml
    name: ${{ matrix.module }}
    secrets: inherit
    with:
      folder: ${{ needs.detect_changes.outputs.module_folder }}
      module: ${{ matrix.module }}

  publish_solution:
    needs: 
    - detect_changes
    - verify_solution
    if: ${{ !failure() && !cancelled() && fromJson(needs.detect_changes.outputs.module_changes) != '' }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect_changes.outputs.module_changes) }}
    
    uses: ./.github/workflows/tmpl.bicep.module.publish.pwsh.yaml
    name: ${{ matrix.module }}
    secrets: inherit
    with:
      folder: ${{ needs.detect_changes.outputs.module_folder }}
      module: ${{ matrix.module }}
      registry: ${{ vars.REGISTRY_NAME }}

      prefix: ${{ github.event_name == 'push' && '' || 'unreleased/' }}     
      immutable: ${{ github.event_name == 'push' }}
