    
name: Dev | Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      what_if_only:
        description: Run a what-if analysis without making changes
        type: boolean
        default: true

  push:
    branches:
      - dev
    paths:
      - 'main.bicep'
      - './params/main.dev.bicepparam'

  pull_request:
    branches:
      - dev
    paths:
      - 'main.bicep'
      - './params/main.dev.bicepparam'
   
jobs:
  deploy_dev:
    name: Deploy Infrastructure Dev
    uses: ./.github/workflows/tmpl.deploy.infrastructure.yaml
    #
    # Set a secret named AZURE_CICDSPN either:
    # - in the environment
    # - or repository scoped
    #
    # The secret should be jsonencoded like this:
    # {
    #   "clientId": "00000000-0000-0000-0000-000000000000",
    #   "objectId": "00000000-0000-0000-0000-000000000000",
    #   "clientSecret": "00000000-0000-0000-0000-000000000000",
    #   "subscriptionId": "00000000-0000-0000-0000-000000000000",
    #   "tenantId": "00000000-0000-0000-0000-000000000000"
    # }
    with:
      scope: subscription
      location: germanywestcentral

      deployment_name: 'sample-dev'
      template_file: ./main.bicep
      parameter_file: ./params/main.dev.bicepparam

      what_if_only: ${{ github.EVENT_NAME  == 'pull_request' || inputs.what_if_only == true }}