name: (Template) Bicep Deployment - Resource Group - PWSH

#
# This is a template for deploying a Bicep file to a resource group using Powershell.
#
# Below is an example of how to use this template in a workflow.
#
#  name: Deploy Infrastructure
#  uses: ./.github/workflows/sample.github.pwsh.group.deploy.yaml
#  secrets:
#    AZURE_DEPLOYMENT_SPN: ${{ secrets.AZURE_CICDSPN }}
#  with:
#    deployment_name: 'sample-${{ inputs.module }}'
#    resource_group: 'sample-${{ inputs.module }}'
#    template_file: ${{ inputs.module }}/example/module.bicep
#    parameter_file: ${{ inputs.module }}/example/module.bicepparam
#

on:
  workflow_call:
    secrets:
      AZURE_DEPLOYMENT_SPN:
        description: "Service Principal for Deployment"
        required: false
      subscription_id:
        description: Set on deployment scope subscription
        required: false
    inputs:
      pwsh_version:
        type: string
        description: The Azure PowerShell version to use
        required: false
        default: "12.1.0"

      deployment_name:
        type: string
        description: The name of the deployment
        required: true

      template_file:
        type: string
        description: Path to the Bicep-File to deploy
        required: true
      parameter_file:
        type: string
        description: path to the bicep parameter file
        required: true

      environment:
        type: string
        description: The github environment to use
        required: false
      run_bicep_tests:
        type: boolean
        description: Run Bicep tests before deployment
        required: false
        default: false


      scope:
        type: string
        description: Deployment Scope. subscription | resourceGroup
        required: true
      resource_group:
        type: string
        description: Set on deployment scope resourceGroup
        required: false
      location:
        type: string
        description: Set on deployment scope subscription
        required: false


      what_if_only:
        type: boolean
        description: Perform what if deployment
        required: false
        default: false
      what_if_result_format
        type: string
        description: The result format to be used on whatif operations
        required: false
        default: 'FullResourcePayloads' # ResourceIdOnly | FullResourcePayloads
      what_if_exclude_change:
        type: string
        description: Exclude change types from What-If results
        required: false
        default: '' # Ignore | NoChange | Deploy | Create | Modify | Delete
      what_if_artifact_name:
        type: string
        description: Name of what_if artifact
        required: false
        default: 'what_if_result'
      what_if_retention_days:
        type: number
        description: Number of days to retain What-If results
        required: false
        default: 7
      ###
      runs-on:
        type: string
        description: The type of the runner
        required: false
        default: "ubuntu-latest"

jobs:
  what_if:
    name: Whatif ${{ inputs.template_file }}
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEPLOYMENT_SPN }}
          enable-AzPSSession: true

      - name: Run Bicep Tests
        uses: azure/powershell@v2
        if: ${{ inputs.run_bicep_tests == true }}
        with:
          azPSVersion: ${{ inputs.pwsh_version }}
          inlineScript: |
            $testFiles = Get-ChildItem -Path "." -Filter *test.bicep -Recurse -Depth 4
            foreach($file in $testFiles) {
              bicep test $file.FullName
            }

      - name: What If ${{ inputs.template_file }}
        uses: azure/powershell@v2
        with:
          azPSVersion: ${{ inputs.pwsh_version }}
          inlineScript: |
            if(-NOT [System.String]::IsNullOrEmpty('${{ secrets.subscription_id }}')) {
              Set-AzContext -Subscription ${{ secrets.subscription_id }}
            }

            $Deployment = @{
              Name                  = "${{ inputs.deployment_name }}"
              TemplateFile          = "${{ inputs.template_file }}"
              TemplateParameterFile = "${{ inputs.parameter_file }}"
              WhatIf                  = $true
              WhatIfResultFormat      = '${{ parameters.WhatIfResultFormat }}'
            }

            if(-NOT [System.String]::IsNullOrEmpty('${{ inputs.what_if_exclude_change }}')) {
              $Deployment.Add('WhatIfExcludeChangeType', '${{ inputs.what_if_exclude_change }}')
            }


            if('${{ inputs.scope }}' -EQ 'subscription') {
              if($null -EQ '${{ inputs.location }}') {
                throw "Subscription Deployment needs a location!"
              }

              $Deployment.Add('location', '${{ inputs.location }}')

              Start-Transcript -Path "./bicep_whatif.txt"
              New-AzSubscriptionDeployment @Deployment
              Stop-Transcript
            } 
            elseif('${{ inputs.scope }}' -EQ 'resourceGroup') {
              if($null -EQ '${{ inputs.resource_group }}') {
                throw "Resource Group Deployment needs a resource group!"
              }

              $Deployment.Add('ResourceGroupName', '${{ inputs.resource_group }}')

              Start-Transcript -Path "./bicep_whatif.txt"
              New-AzResourceGroupDeployment @Deployment
              Stop-Transcript
            } else {
              throw "Invalid Scope ${{ inputs.scope }}!"
            }

      - name: Upload What-If Results
        uses: actions/upload-artifact@v4
        if: ${{ inputs.what_if_artifact_name != '' }}
        with:
          name: ${{ inputs.what_if_artifact_name }}
          path: ./bicep_whatif.txt
          retention-days: ${{ inputs.what_if_retention_days }}



  deploy_bicep:
    needs:
    - what_if
    if: ${{ inputs.what_if_only == false }}
    name: Deploy ${{ inputs.template_file }}
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEPLOYMENT_SPN }}
          enable-AzPSSession: true

      - name: Deploy ${{ inputs.template_file }}
        uses: azure/powershell@v2
        with:
          azPSVersion: ${{ inputs.pwsh_version }}
          inlineScript: |

            if(-NOT [System.String]::IsNullOrEmpty('${{ secrets.subscription_id }}')) {
              Set-AzContext -Subscription ${{ secrets.subscription_id }}
            }

            $Deployment = @{
              Name                  = "${{ inputs.deployment_name }}"
              TemplateFile          = "${{ inputs.template_file }}"
              TemplateParameterFile = "${{ inputs.parameter_file }}"
            }


            if('${{ inputs.scope }}' -EQ 'subscription') {
              if([System.String]::IsNullOrEmpty('${{ inputs.location }}')) {
                throw "Subscription Deployment needs a location!"
              }

              $Deployment.Add('location', '${{ inputs.location }}')
              New-AzSubscriptionDeployment @Deployment
            } 
            elseif('${{ inputs.scope }}' -EQ 'resourceGroup') {
              if([System.String]::IsNullOrEmpty('${{ inputs.resource_group }}')) {
                throw "Resource Group Deployment needs a resource group!"
              }

              $Deployment.Add('ResourceGroupName', '${{ inputs.resource_group }}')
              New-AzResourceGroupDeployment @Deployment
            } else {
              throw "Invalid Scope ${{ inputs.scope }}!"
            }