name: Detect and Publish Module Changes

# NOTE:
# This may need to be adjusted to your used pool
pool:
  name: "Azure Pipelines"
  vmImage: "ubuntu-latest"

# NOTE:
# Triggers on Pull Request are configured via branch policies in Azure DevOps
trigger:
  branches:
    include:
      - dev
      - main
      - master
  paths:
    include:
      - modules/**

parameters:
  # Will fail as a precaution when too many modules are being deployed at once. Increase to confirm your intent.
  - name: concurrencyLimit
    type: number
    default: 5

variables:
  DEPLOY_SCRIPT: ./.scripts/deploy.ps1
  FOLDER_PREFIX: "modules/"
  DEFAULT_LOCATION: "westeurope"

stages:
  - template: stage/tmpl.bicep.module.publish.yaml
    parameters:
      stage: Test

      condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/dev')
      serviceConnection: project-connection

      # Pipeline will fail when too many modules are being deployed at once
      # This is to prevent accidental runs deploying too many modules
      concurrencyLimit: ${{ parameters.concurrencyLimit }}

      # Customize when to deploy and publish
      # The Following conditions are also set by default when removed.
      testDeployCondition: eq(variables['Build.Reason'], 'PullRequest')
      publishModuleCondition: ne(variables['Build.Reason'], 'PullRequest')

      # Runs test deployment when set.
      deployScript: $(DEPLOY_SCRIPT)
      folderPrefix: $(FOLDER_PREFIX)
      defaultLocation: $(DEFAULT_LOCATION)

      registryName: acr-sample-dev

      # Allow overwriting existing image tags. Defaults to true
      # allowImageOverwrite: false
      
      # Set the registry image to be immutable. 
      # Prevents any changes to the image in the ACR.
      # When this is true, even allowImageOverwrite can NOT overwrite the image
      setImageImmutable: false

      # Sets a image prefix to the generated image name
      # image name is generate from module path: utility/naming/schema
      # imagePrefix: custom/image-prefix

      # Sets temporary IP rules on the ACR
      # Use this when the ACR network is restricted
      setTemporaryIpRules: |
        acr-sample-dev


  - template: stage/tmpl.bicep.module.publish.yaml
    parameters:
      # Optionally depend on other stages
      # Will not execute if the dependent stage was skipped!!!
      # dependsOn:
      # - Test
      stage: Prod

      condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/master')
      serviceConnection: project-connection

      # Pipeline will fail when too many modules are being deployed at once
      # This is to prevent accidental runs deploying too many modules
      concurrencyLimit: ${{ parameters.concurrencyLimit }}
  
      # Customize when to deploy and publish
      # The Following conditions are also set by default when removed.
      testDeployCondition: eq(variables['Build.Reason'], 'PullRequest')
      publishModuleCondition: ne(variables['Build.Reason'], 'PullRequest')

      # Runs test deployment when set.
      deployScript: $(DEPLOY_SCRIPT)
      folderPrefix: $(FOLDER_PREFIX)
      defaultLocation: $(DEFAULT_LOCATION)

      registryName: acr-sample-prod

      # Allow overwriting existing image tags. Defaults to true
      allowImageOverwrite: false

      # Set the registry image to be immutable. 
      # Prevents any changes to the image in the ACR.
      # When this is true, even allowImageOverwrite can NOT overwrite the image
      setImageImmutable: false

      # Sets a image prefix to the generated image name
      # image name is generate from module path: utility/naming/schema
      # imagePrefix: custom/image-prefix

      # Sets temporary IP rules on the ACR
      # Use this when the ACR network is restricted
      setTemporaryIpRules: |
        acr-sample-prod
