    
name: Test | Detect and Publish Module Changes

# Define variables in github actions
# REGISTRY_NAME: The name of the container registry to use for publishing images.
# DEFAULT_LOCATION: The default location to use for resources.

on:
  workflow_dispatch:
    inputs:
      concurrency_limit:
        description: Will fail when too many modules are deployed at once. Increase to confirm your intent.
        type: number
        required: false
        default: 5

  push:
    branches:
      - master
    paths:
      - modules/**

  pull_request:
    branches:
      - master
    paths:
      - 'modules/**'
      - '!modules/**/example/**'
      - '!modules/**/README.md'

          
env:
  FOLDER_PREFIX: modules/

jobs:
  detect_changes:
    name: Detect changes
    runs-on: 'ubuntu-latest'
    outputs:
      module_changes: ${{ steps.get_diff.outputs.module_changes }}
      module_folder: ${{ steps.get_diff.outputs.module_folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Git Diff
        id: get_diff
        uses: ./.github/actions/tmpl.bicep.detectChanges
        with:
          concurrency_limit: ${{ inputs.concurrency_limit }}
          folder_prefix: ${{ env.FOLDER_PREFIX }}

  verify_solution:
    needs: 
    - detect_changes
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect_changes.outputs.module_changes) }}
    
    uses: ./.github/workflows/tmpl.bicep.module.verify.pwsh.yaml
    name: ${{ matrix.module.module_path }}
    secrets: inherit
    #
    # Set a secret named AZURE_CICDSPN either:
    # - in the environment
    # - or repository scoped
    #
    # The secret should be jsonencoded like this:
    # {
    #   "clientId": "00000000-0000-0000-0000-000000000000",
    #   "objectId": "00000000-0000-0000-0000-000000000000",
    #   "clientSecret": "00000000-0000-0000-0000-000000000000",
    #   "subscriptionId": "00000000-0000-0000-0000-000000000000",
    #   "tenantId": "00000000-0000-0000-0000-000000000000"
    # }
    with:
      # environment: prod

      default_location: ${{ inputs.default_location }}
      folder_prefix: ${{ matrix.module.folder_prefix }}
      module_path: ${{ matrix.module.module_path }}

      # set_temporary_ip_rules: |
      #   acr-sample-test


  publish_solution:
    needs: 
    - detect_changes
    - verify_solution
    if: ${{ github.event_name == 'push' && !failure() && !cancelled() }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect_changes.outputs.module_changes) }}
    
    uses: ./.github/workflows/tmpl.bicep.module.publish.pwsh.yaml
    name: ${{ matrix.module.module_path }}
    secrets: inherit
    with:
      # environment: test
      folder_prefix: ${{ matrix.module.folder_prefix }}
      module_path: ${{ matrix.module.module_path }}
      registry_name: ${{ vars.REGISTRY_NAME }}

      image_tag: ${{ matrix.module.version }}
      image_name: ${{ matrix.module.module_path }}
      image_prefix: ${{ github.event_name == 'push' && '' || 'unreleased/' }}    
      
      allow_image_overwrite: true
      set_image_immutable: false

      # set_temporary_ip_rules: |
      #   acr-sample-test


  update_tags:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event_name == 'push' && success() }}
    needs:
    - publish_solution
    steps:
      - name: Set Change Marker Tag
        uses: ./.github/actions/tmpl.bicep.setChangeMarker