    
name: Detect and Publish Module Changes

on:
  workflow_dispatch:
    inputs:
      concurrency_limit:
        description: Will fail when too many modules are deployed at once. Increase to confirm your intent.
        type: number
        required: true
        default: 5

  push:
    branches:
      - master
    paths:
      - modules/**

  pull_request:
    branches:
      - master
    paths:
      - 'modules/**'
      - '!modules/**/example/**'
      - '!modules/**/README.md'

          
env:
  FOLDER_PREFIX: modules/
  DEFAULT_LOCATION: westeurope

jobs:
  detect_changes:
    name: Detect changes
    runs-on: 'ubuntu-latest'
    outputs:
      module_changes: ${{ steps.get_diff.outputs.module_changes }}
      module_folder: ${{ steps.get_diff.outputs.module_folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Git Diff
        id: get_diff
        uses: ./.github/actions/tmpl.bicep.detectChanges
        with:
          concurrency_limit: ${{ inputs.concurrency_limit }}
          folder_prefix: ${{ env.FOLDER_PREFIX }}

  verify_solution:
    needs: 
    - detect_changes
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect_changes.outputs.module_changes) }}
    
    uses: ./.github/workflows/tmpl.bicep.module.verify.pwsh.yaml
    name: ${{ matrix.module }}
    secrets: inherit
    #
    # Set a secret named AZURE_CICDSPN either:
    # - in the environment
    # - or repository scoped
    #
    # The secret should be jsonencoded like this:
    # {
    #   "clientId": "00000000-0000-0000-0000-000000000000",
    #   "objectId": "00000000-0000-0000-0000-000000000000",
    #   "clientSecret": "00000000-0000-0000-0000-000000000000",
    #   "subscriptionId": "00000000-0000-0000-0000-000000000000",
    #   "tenantId": "00000000-0000-0000-0000-000000000000"
    # }
    with:
      # environment: prod

      folder_prefix: ${{ needs.detect_changes.outputs.module_folder }}
      module_path: ${{ matrix.module }}

      default_location: ${{ env.DEFAULT_LOCATION }}

      # set_temporary_ip_rules: |
      #   acr-sample-test


  publish_solution:
    needs: 
    - detect_changes
    - verify_solution
    if: ${{ github.event_name == 'push' && !failure() && !cancelled() }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect_changes.outputs.module_changes) }}
    
    uses: ./.github/workflows/tmpl.bicep.module.publish.pwsh.yaml
    name: ${{ matrix.module }}
    secrets: inherit
    with:
      # environment: test
      folder_prefix: ${{ needs.detect_changes.outputs.module_folder }}
      module_path: ${{ matrix.module }}
      registry: ${{ vars.REGISTRY_NAME }}

      image_prefix: ${{ github.event_name == 'push' && '' || 'unreleased/' }}
      set_immutable: false

      # set_temporary_ip_rules: |
      #   acr-sample-test


  update_tags:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event_name == 'push' && success() }}
    needs:
    - publish_solution
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Update Tags
        shell: pwsh
        run: |
          $branch   = "${{ github.ref_name }}" # git branch --show-current
          $tagName  = "meta-$branch-last-successful-publish"
          $message  = "DO NOT DELETE | Tracks when commit for detecting module changes

          git config user.name "GitHubActions"
          git config user.email "actions@github.com"

          # Make sure we're on the branch and up-to-date
          git fetch origin $branch
          git checkout $branch
          git reset --hard origin/$branch

          # Create or update the tag
          git tag $tagName -m "$message" --force
          git push origin $tagName --force