parameters:
  - name: condition
    type: string
    default: true
  - name: stage
    type: string
  - name: displayName
    type: string
    default: ''
  - name: serviceConnection
    type: string
  - name: variableGroup
    type: string
    default: ''

  # General deployment parameter
  - name: WhatIfOnly
    type: string
    default: true
  - name: WhatIfResultFormat
    type: string
    default: 'FullResourcePayloads' # ResourceIdOnly | FullResourcePayloads
  - name: WhatIfExcludeChange
    type: string
    default: '' # Ignore | NoChange | Deploy | Create | Modify | Delete

  # others
  - name: showTree
    type: boolean
    default: false
  - name: runBicepTests
    type: boolean
    default: false
  - name: azurePowerShellVersion
    type: string
    default: LatestVersion

stages:
  - stage: ${{ parameters.stage }}
    condition: ${{ parameters.condition }}
    displayName: Deploy ${{ parameters.stage }}
    variables:
      - ${{ if ne(parameters.variableGroup, '') }}:
          - group: ${{ parameters.variableGroup }}
    jobs:
      #////////////////////////////////////////////////////////////
      #////// WhatIf
      - deployment: what_if_${{ parameters.stage }}
        displayName: WhatIf Bicep ${{ parameters.stage }}
        environment: ${{ parameters.stage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - ${{ each subModule in parameters.checkoutSubModules }}:
                    - checkout: ${{ subModule.alias }}
                      path: s/$(Build.Repository.Name)/${{ subModule.path }}
                #////////////////////////////////////////////////////////////
                #////// Tree Command
                - script: |
                    sudo apt-get update
                    sudo apt-get install -y tree
                  displayName: Install tree
                  condition: ${{ parameters.showTree }}
                - script: |
                    tree $(Build.SourcesDirectory)
                  condition: ${{ parameters.showTree }}
                  displayName: Show directory
                #////////////////////////////////////////////////////////////
                #////// Bicep Tests
                - task: AzurePowerShell@5
                  displayName: Bicep Test ${{ parameters.stage }}
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    azurePowerShellVersion: ${{ parameters.azurePowerShellVersion }}
                    ScriptType: inlineScript
                    pwsh: true
                    inline: |
                      $testFiles = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Filter *test.bicep -Recurse -Depth 4
                      foreach($file in $testFiles) {
                        bicep test $file.FullName
                      }
                #////////////////////////////////////////////////////////////
                #////// WhatIf
                - task: AzurePowerShell@5
                  displayName: WhatIf Bicep ${{ parameters.stage }}
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    azurePowerShellVersion: ${{ parameters.azurePowerShellVersion }}
                    ScriptType: inlineScript
                    pwsh: true
                    inline: |
                        if(-NOT [System.String]::IsNullOrEmpty('$(SUBSCRIPTION_ID)')) {
                           Write-Host 'Subscription: $(SUBSCRIPTION_ID)'
                           Set-AzContext -Subscription $(SUBSCRIPTION_ID)
                        }

                        $Deployment = @{
                            Name                    = '${{ parameters.stage }}.$(DEPLOYMENT_NAME)'
                            TemplateFile            = '$(TEMPLATE_FILE)'
                            TemplateParameterFile   = '$(PARAMETERS_FILE)'
                            WhatIf                  = $true
                            WhatIfResultFormat      = '${{ parameters.WhatIfResultFormat }}'
                        }

                        if(-NOT [System.String]::IsNullOrEmpty('${{ parameters.WhatIfExcludeChange }}')) {
                            $Deployment.Add('WhatIfExcludeChangeType', '${{ parameters.WhatIfExcludeChange }}')
                        }


                        if('$(SCOPE)' -EQ 'subscription') {
                          [System.String]::IsNullOrEmpty('$(LOCATION)') {
                            throw "Subscription Deployment needs a location!"
                          }

                          $Deployment.Add('location', '$(LOCATION)')

                          Start-Transcript -Path "$(Build.ArtifactStagingDirectory)/bicep_whatif.txt"
                          New-AzSubscriptionDeployment @Deployment
                          Stop-Transcript
                        } 
                        elseif('$(SCOPE)' -EQ 'resourceGroup') {
                          if([System.String]::IsNullOrEmpty('$(RESOURCE_GROUP)')) {
                            throw "Resource Group Deployment needs a resource group!"
                          }

                          $Deployment.Add('ResourceGroupName', '$(RESOURCE_GROUP)')

                          Start-Transcript -Path "$(Build.ArtifactStagingDirectory)/bicep_whatif.txt"
                          New-AzResourceGroupDeployment @Deployment
                          Stop-Transcript
                        } else {
                          throw "Invalid Scope $(SCOPE)!"
                        }

                - task: PublishBuildArtifacts@1
                  displayName: "Bicep WhatIf Artifact"
                  inputs:
                    targetPath: "$(Build.ArtifactStagingDirectory)/bicep_whatif.txt"
                    artifactName: "bicep_whatif_${{ parameters.stage }}"

      - job: approve_${{ parameters.stage }}
        condition: and(succeeded(), eq(${{ parameters.WhatIfOnly }}, false))
        dependsOn: what_if_${{ parameters.stage }}
        displayName: Approve
        pool: server
        steps:
          - task: ManualValidation@0
            displayName: Manual Validation
            timeoutInMinutes: 1440

      #////////////////////////////////////////////////////////////
      #////// Deploy
      - deployment: deployment_${{ parameters.stage }}
        condition: and(succeeded(), eq(${{ parameters.WhatIfOnly }}, false))
        dependsOn: approve_${{ parameters.stage }}
        displayName: Deploy Bicep ${{ parameters.stage }}
        environment: ${{ parameters.stage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - ${{ each subModule in parameters.checkoutSubModules }}:
                    - checkout: ${{ subModule.alias }}
                      path: s/$(Build.Repository.Name)/${{ subModule.path }}
                - task: AzurePowerShell@5
                  displayName: WhatIf Bicep ${{ parameters.stage }}
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    azurePowerShellVersion: ${{ parameters.azurePowerShellVersion }}
                    ScriptType: inlineScript
                    pwsh: true
                    inline: |
                        if(-NOT [System.String]::IsNullOrEmpty('$(SUBSCRIPTION_ID)')) {
                           Write-Host 'Subscription: $(SUBSCRIPTION_ID)'
                           Set-AzContext -Subscription $(SUBSCRIPTION_ID)
                        }

                        $Deployment = @{
                            Name                    = '${{ parameters.stage }}.$(DEPLOYMENT_NAME)'
                            TemplateFile            = '$(TEMPLATE_FILE)'
                            TemplateParameterFile   = '$(PARAMETERS_FILE)'
                        }

                        if('$(SCOPE)' -EQ 'subscription') {
                          if([System.String]::IsNullOrEmpty('$(LOCATION)')) {
                            throw "Subscription Deployment needs a location!"
                          }

                          $Deployment.Add('location', '$(LOCATION)')

                          New-AzSubscriptionDeployment @Deployment -Verbose
                        } 
                        elseif('$(SCOPE)' -EQ 'resourceGroup') {
                          if([System.String]::IsNullOrEmpty('$(RESOURCE_GROUP)')) {
                            throw "Resource Group Deployment needs a resource group!"
                          }

                          $Deployment.Add('ResourceGroupName', '$(RESOURCE_GROUP)')

                          New-AzResourceGroupDeployment @Deployment -Verbose
                        } else {
                          throw "Invalid Scope $(SCOPE)!"
                        }
