    
name: Deploy Infrastructure Dev / Test

on:
  workflow_dispatch:
    inputs:
      what_if_only:
        description: Run a what-if analysis without making changes
        type: boolean
        default: true

  push:
    branches:
      - dev
    paths:
      - 'main.bicep'
      - './params/main.dev.bicepparam'

  pull_request:
    branches:
      - dev
    paths:
      - 'main.bicep'
      - './params/main.dev.bicepparam'
   
jobs:
  deploy_dev:
    name: Deploy Infrastructure Dev
    uses: ./.github/workflows/tmpl.deploy.infrastructure.yaml
    secrets:
      AZURE_DEPLOYMENT_SPN: ${{ secrets.AZURE_CICDSPN }}
    with:
      scope: subscription
      location: germanywestcentral

      name: 'sample-dev'
      template_file: ./main.bicep
      parameter_file: ./params/main.dev.bicepparam

      what_if_only: ${{ github.EVENT_NAME  == 'pull_request' || inputs.what_if_only == true }}