name: Publish PowerShell Module

on:
  workflow_dispatch:
    inputs:
      skip_publish:
        description: 'Skip publishing the module'
        required: false
        default: true
        type: boolean

env:
  MODULE_NAME: BicepStarterPipelines
  GALLERY_URL: https://www.powershellgallery.com/api/v2/package/
    
jobs:
  #//////////////////////////////////////////////////////
  # Run Tests
  # 
  run_pester:
    name: Run Pester Tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        # [ubuntu-latest, macos-latest] 
        # maybe support for other PLatforms in the future
        # no gurantee to work on other platforms
        os: [windows-latest, ubuntu-latest, macos-latest] 

    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        shell: pwsh
        run: Install-Module -Name Pester -Force -SkipPublisherCheck
      - name: Run Pester Tests
        shell: pwsh
        run: |
          $Global:BicepStarterPipelinesNonInteractive = $true
          Import-Module ./${{ env.MODULE_NAME }}
          # Invoke-Pester -Path ./${{ env.MODULE_NAME }}.Tests -Output Detailed -CI

  #//////////////////////////////////////////////////////
  # Pack Module
  # 
  pack_module:
    needs:
    - run_pester
    name: Pack Module
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Pack Module
        shell: pwsh
        run: |
          $psd1 = Import-PowerShellDataFile -Path "./${{ env.MODULE_NAME }}/BicepStarterPipelines.psd1"

          @"
          <?xml version="1.0"?>
          <package>
              <metadata>
                  <id>${{ env.MODULE_NAME }}</id>
                  <version>$($psd1.ModuleVersion)</version>
                  <authors>$($psd1.Author)</authors>
                  <owners>$($psd1.Author)</owners>
                  <requireLicenseAcceptance>false</requireLicenseAcceptance>
                  <description>$($psd1.Description)</description>
                  <copyright>(c) $($psd1.Author).</copyright>
                  <tags>$($psd1.PrivateData.PSData.Tags -join " ")</tags>
                  <projectUrl>$($psd1.PrivateData.PSData.ProjectUri)</projectUrl>
              </metadata>
          </package>
          "@ | Out-File -FilePath "./${{ env.MODULE_NAME }}/BicepStarterPipelines.nuspec"

          nuget pack "./${{ env.MODULE_NAME }}" -OutputDirectory "./${{ env.MODULE_NAME }}"
    
      - name: Upload nupkg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: module-package
          path: "./${{ env.MODULE_NAME }}"

  #//////////////////////////////////////////////////////
  # Publish to PowerShell Gallery
  # 
  publish:
    if: inputs.skip_publish == false
    needs: 
    - pack_module
    - run_pester
    runs-on: windows-latest
    name: Publish to PowerShell Gallery
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: module-package
          path: "./${{ env.MODULE_NAME }}"
      - name: Push Module
        shell: pwsh
        run: |
          $nupkg = Get-ChildItem -Path "./${{ env.MODULE_NAME }}" -Filter *.nupkg
          nuget push $nupkg -ApiKey ${{ secrets.PS_GALLERY_TOKEN }} -Source ${{ env.GALLERY_URL }}